bakpage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    url(r'^markdownx/', include('markdownx.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

website/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import *
from . import views

app_name = "website"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    # path('l/', LandingPage.as_view(), name='landing'),
    path("about/", AboutView.as_view(), name="about"),
    path("blog/", BlogView.as_view(), name="blog"),
    path("blog/<slug>/", BlogDetailView.as_view(), name="blog"),
    path("project/", ProjectListView.as_view(), name="project"),
    path("service/", ServiceListView.as_view(), name="service"),
    path("service/<slug>/", ServiceView.as_view(), name="service"),
    path("project/<slug>/", ProjectDetailView.as_view(), name="project"),
]

website/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.shortcuts import reverse
from taggit.managers import TaggableManager


class Service(models.Model):
    name = models.CharField(max_length=30, unique=True)
    image = models.ImageField(null=True, blank=True)
    icons = models.CharField(max_length=30, blank=True, null=True)
    description = MarkdownxField()
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("website:service", kwargs={"slug": self.slug})

    def formatted_markdown(self):
        return markdownify(self.description)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url


class Category(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=150)
    image = models.ImageField()
    image_1 = models.ImageField(blank=True, null=True)
    image_2 = models.ImageField(blank=True, null=True)
    image_3 = models.ImageField(blank=True, null=True)
    link = models.CharField(max_length=100, blank=True, null=True)
    client = models.CharField(max_length=100, blank=True, null=True)
    description = MarkdownxField()
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True
    )
    slug = models.SlugField()
    tags = TaggableManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("website:project", kwargs={"slug": self.slug})

    def formatted_markdown(self):
        return markdownify(self.description)

    @property
    def image1URL(self):
        try:
            url = self.image_1.url
        except:
            url = ""
        return url

    @property
    def image2URL(self):
        try:
            url = self.image_2.url
        except:
            url = ""
        return url

    @property
    def image3URL(self):
        try:
            url = self.image_3.url
        except:
            url = ""
        return url


class Blog(models.Model):
    title = models.CharField(max_length=300)
    author = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField()
    text = MarkdownxField()
    quote = MarkdownxField()
    slug = models.SlugField()
    tags = TaggableManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("website:blog", kwargs={"slug": self.slug})

    def formatted_markdown(self):
        return markdownify(self.text)

website/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView, View, CreateView
from django.http import HttpResponse, HttpResponseRedirect
from taggit.models import Tag
from .models import *


class HomeView(View):
    #common_tags = Post.tags.most_common()[:4]

    def get(self, request):
        services = Service.objects.all()
        projects = Project.objects.all()
        blogs = Blog.objects.all()
        template_name = "home.html"
        context = {'services': services, 'projects': projects, 'blogs': blogs}
        return render(request, template_name, context)

class LandingPage(View):
    def get(self, request, *args, **kwargs):
        template_name = "new/main.html"
        return render(request, template_name,)

class AboutView(View):
    def get(self, request):
        services = Service.objects.all()
        template_name = "about.html"
        context = {'services': services,}
        return render(request, template_name, context)


class ServiceView(DetailView):
    model = Service
    template_name = "service-single.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service_list'] = Service.objects.all()
        return context


class ProjectDetailView(DetailView):
    model = Project
    template_name = "project-single.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project_list'] = Project.objects.all()
        return context


class ProjectListView(ListView):
    model = Project
    template_name = "project-list.html"

class ServiceListView(ListView):
    model = Service
    template_name = "service-list.html"

class BlogView(View):
    def get(self, request):
        blogs = Blog.objects.all()
        template_name = "blog-page.html"
        context = {'blogs': blogs}
        return render(request, template_name, context)


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog-single.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog_list'] = Blog.objects.all()
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>BakPage Labs</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="msapplication-TileColor" content="#E9204F">
  <meta name="theme-color" content="#E9204F">
  <link rel="apple-touch-icon" sizes="180x180" href="assets/images/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon-16x16.png">
  <!--   <link rel="manifest" href="assets/images/site.webmanifest">
  <link rel="mask-icon" href="images/safari-pinned-tab.svg" color="#E9204F"> -->
  <script data-ad-client="ca-pub-8128509305831596" async
    src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <link rel="stylesheet" href="{% static 'assets/css/normalize.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/pr.animation.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/uikit.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/pixeicons.css' %}" />
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
  {% include 'partials/messages.html' %}
  <!-- Content Row -->
  {% block content %}

  {% endblock %}
  <div id="pr__contact__form" class="pr__contact__form pr__dark uk-modal-full" data-uk-modal="">
    <div class="uk-modal-dialog" data-uk-height-viewport="">
      <div class="form-outer">
        <div class="uk-container uk-container-xsmall">
          <div class="form-inner uk-position-relative">
            <button class="uk-modal-close-full" type="button" data-uk-close="ratio: 2;"><span>Close</span></button>
            <h2 class="uk-modal-title uk-h1">Let's Talk?</h2>
            <p>Let’s make something awesome together</p>
            <form class="pr__contact pr__form" action="mailto:info@bakpagelabs.com" method="POST">
              <div class="pr__form__group">
                <label for="name">Your Name <span class="required">*</span></label>
                <input class="pr-input" id="name" name="name" type="text" />
              </div>
              <div class="pr__form__group">
                <label for="email">Your E-Mail <span class="required">*</span></label>
                <input class="pr-input" id="email" name="email" type="text" />
              </div>
              <!-- 
              <div class="pr__form__group">
                <label for="subject">Your Subject <span class="required">*</span></label>
                <input class="pr-input" id="subject" name="subject" type="text" />
              </div>
              <div class="pr__form__group">
                <label for="budget">What's your budget range?</label>
                <select class="uk-select" id="budget" name="budget">
                  <option>&nbsp;</option>
                  <option>Low budget</option>
                  <option>$1,000 — $2,000</option>
                  <option>$2,000 — $5,000</option>
                  <option>$5,000 — $10,000</option>
                  <option>$10,000+</option>
                </select>
              </div> -->
              <div class="pr__form__group">
                <label for="message">Your message <span class="required">*</span></label>
                <textarea class="pr-textarea" id="message" name="message"></textarea>
              </div>
              <p class="pr__form__group uk-margin-large">

              </p><input class="uk-button uk-button-large uk-button-primary" type="submit" name="submit"
                value="Submit"></input>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div><!-- Contact Form Popup End -->



  <!-- Needed Scripts -->
  <script language="JavaScript">
    var frmvalidator = new Validator("contactform");
    frmvalidator.addValidation("name", "req", "Please provide your name");
    frmvalidator.addValidation("email", "req", "Please provide your email");
    frmvalidator.addValidation("email", "email",
      "Please enter a valid email address");
  </script>

  <script src="{% static 'assets/js/jquery.min.js'%}"></script>
  <script src="{% static 'assets/js/anime.min.js'%}"></script>
  <script src="{% static 'assets/js/pr.animation.js'%}"></script>
  <script src="{% static 'assets/js/uikit.min.js'%}"></script>
  <script src="{% static 'assets/js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'assets/js/validate.js'%}"></script>
  <script src="{% static 'assets/js/main.js'%}"></script>
</body>

</html>

templates/blog-page.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<body class="page-template page-template-blog-chess single page">
    {% include 'partials/loader.html'%}

    {% include 'partials/mobile_nav.html'%}
    <!-- Mobile Nav End -->

    <div class="pr__wrapper" id="site-wrapper">
        <div class="pr__hero__wrap pr__dark" style="background-image: url('../static/assets/images/hero_03.jpg');"
            data-uk-parallax="bgy: -200" id="site-hero">
            {% include 'partials/header.html' %}

            <section class="pr__hero uk-section" id="pr__hero">
                <div class="uk-container">
                    <div class="section-inner">
                        <div class="hero-content uk-grid" data-uk-grid="">
                            <div class="uk-width-2-3@s">
                                <hr class="line pr__hr__secondary">
                                <h2 class="page-title h1">Our Thinking.</h2>
                                <ul class="breadcrumbs uk-breadcrumb">
                                    <li><a href="/">Home</a></li>
                                    <li><span>Blog Listing</span></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!-- Site Hero End -->

        </div><!-- Hero Wrap End -->

        <div class="pr__content" id="site-content">

            <hr class="pr__vr__section">

            <div class="pr__primary uk-section uk-section-large full-width" id="site-primary">
                <div class="outer">
                    <div class="uk-container uk-position-relative">
                        <div class="inner uk-grid uk-grid-large uk-grid-match" data-uk-grid="">
                            <div class="uk-width-expand">
                                <main class="pr__main" id="site-main">
                                    <section class="blog-listing chess-layout outer" id="pr__blog__chess">
                                        <div class="inner uk-grid uk-grid-collapse uk-child-width-1-3@l"
                                            data-uk-grid="">
                                            {% for blog in blogs %}
                                            <div class="item">
                                                <article class="post type-post">
                                                    <div class="outer uk-card">
                                                        <div
                                                            class="featured-image uk-card-media-right uk-cover-container">
                                                            <div class="image pr__image__cover pr__ratio__square"
                                                                data-src="{{blog.image.url}}" data-uk-img="">
                                                            </div>
                                                            <a href="{{blog.get_absolute_url}}" class="link"></a>
                                                        </div>
                                                        <div class="inner uk-card-body">
                                                            <div class="top">
                                                                <a class="category"
                                                                    href="{{blog.get_absolute_url}}">{{blog.tags.name}}</a>
                                                                <h3 class="title uk-h4"><a
                                                                        href="{{blog.get_absolute_url}}">{{blog.title}}</a>
                                                                </h3>
                                                                <p class="description">{{blog.text|truncatewords:30}}
                                                                </p>
                                                            </div>
                                                            <div class="bottom">
                                                                <ul class="meta">
                                                                    <li class="meta-date">{{blog.date}}</li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </article>
                                            </div>
                                            {% endfor %}
                                        </div>
                                    </section>
                                    <!-- <section
                                        class="blog-pagination pr__load__more uk-flex uk-flex-center uk-margin-xlarge-top">
                                        <a class="button uk-button uk-button-large uk-button-default" href="#">Load More
                                            Posts</a>
                                    </section> -->
                                </main>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <hr class="pr__vr__section">

        </div><!-- Site Content End -->
        {% include 'partials/footer.html'%}
        <!-- Site Footer End-->

    </div><!-- Site Wrapper End -->


</body>
{% endblock %}

templates/blog-single.html
{% extends 'base.html' %}
{% load static humanize%}
{% load crispy_forms_tags %}
{% block content %}

<body class="page-template page-template-full single single-post">
    {% include 'partials/loader.html'%}

    {% include 'partials/mobile_nav.html'%}
    <!-- Mobile Nav End -->

    <div class="pr__wrapper" id="site-wrapper">
        <div class="pr__hero__wrap pr__dark" style="background-image: url('../static/assets/images/hero_03.jpg');"
            data-uk-parallax="bgy: -200" id="site-hero">
            {% include 'partials/header.html' %}

            <section class="pr__hero uk-section" id="pr__hero">
                <div class="uk-container">
                    <div class="section-inner">
                        <div class="hero-content">
                            <a class="category" href="blog/">Blog</a>
                            <h2 class="page-title uk-h1">{{object.title}}</h2>
                        </div>
                    </div>
                </div>
            </section><!-- Site Hero End -->

        </div><!-- Hero Wrap End -->

        <div class="pr__content" id="site-content">

            <div class="pr__primary uk-section uk-section-medium" id="site-primary">
                <div class="outer">
                    <div class="uk-container uk-position-relative">
                        <div class="inner uk-grid uk-grid-large uk-grid-match" data-uk-grid="">
                            <div class="uk-width-expand">
                                <main class="pr__main" id="site-main">
                                    <article class="uk-article post type-post single-post">

                                        <div class="outer uk-grid uk-grid-large uk-flex" data-uk-grid="">
                                            <div class="inner uk-width-expand">
                                                <div class="entry-body">
                                                    <p class="uk-text-lead">Bring to the table win-win survival
                                                        strategies to ensure proactive domination. At the end of the
                                                        day, going forward,
                                                    </p>

                                                    <h3 class="uk-h3">{{object.title}}</h3>

                                                    <figure class="wp-caption aligncenter" data-uk-lightbox="">
                                                        <a href="{{object.image.url}}">
                                                            <img src="{{object.image.url}}"
                                                                alt="Improving User Experience and Website Performance with Progressive JPEGs"></a>
                                                        <figcaption class="wp-caption-text">Success is largely a matter
                                                            of holding on after others have let go.</figcaption>
                                                    </figure>
                                                    <p>{{object.text|safe}}</p>
                                                    <p>{{object.formatted_markdown|safe }}</p>
                                                    <br>
                                                    <blockquote class="uk-text-left">
                                                        <p>{{object.quote}}</p>
                                                        <footer><strong>{{object.author}}</strong> – CEO, Strategy
                                                            Director
                                                        </footer>
                                                    </blockquote>

                                                </div>
                                            </div>
                                            <div class="pr__entry__sidebar uk-width-1-5@l uk-flex-first@l">
                                                <div class="pr__entry__meta pr__vr">
                                                    <ul class="content uk-list uk-list-divider">
                                                        <li class="author">
                                                            <strong>Written by:</strong>
                                                            <span>{{object.author}}</span>
                                                        </li>
                                                        <li class="date">
                                                            <strong>Posted on:</strong>
                                                            <span>{{object.created_at|naturaltime}}</span>
                                                        </li>
                                                        <li class="category">
                                                            <strong>Tags:</strong>
                                                            {% for tag in object.tags.all %}
                                                            <span><a href="#">{{ tag.name }}</a></span>
                                                            {% endfor %}
                                                        </li>
                                                    </ul>
                                                </div>
                                                <div class="pr__entry__share pr__small">
                                                    <a href="#" data-uk-tooltip="Share on Twitter"><i
                                                            class="icon pr-logo-twitter"></i></a>
                                                    <a href="#" data-uk-tooltip="Share on Facebook"><i
                                                            class="icon pr-logo-facebook"></i></a>
                                                    <a href="#" data-uk-tooltip="Share on Xing"><i
                                                            class="icon pr-logo-xing"></i></a>
                                                </div>
                                            </div>
                                        </div>

                                    </article>
                                </main>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <section class="pr__blog pr__section section-slider uk-section uk-section-large uk-section-default"
                id="pr__blog">
                <div class="section-outer">
                    <div class="section-heading">
                        <div class="uk-container">
                            <div class="inner">
                                <div>
                                    <hr class="line pr__hr__secondary">
                                    <h2 class="title uk-h3 pr__heading__secondary">Related Posts.</h2>
                                </div>
                            </div>
                        </div><!-- Container End -->
                    </div><!-- Heading End -->
                    <div class="section-inner">
                        <div class="uk-container">
                            <div class="blog-listing style-two blog-slider uk-grid uk-grid-collapse uk-child-width-1-3@m"
                                data-uk-grid="">
                                {% for object in blog_list%}
                                <div class="item">
                                    <article class="post type-post active">
                                        <div class="outer">
                                            <div class="featured-image">
                                                <div class="image pr__image__cover" data-src="{{object.image.url}}"
                                                    data-uk-img=""></div>
                                            </div>
                                            <div class="inner">
                                                <div class="top">
                                                    <a class="category" href="#">Careers</a>
                                                    <h3 class="title uk-h4"><a href="#">{{object.title}}</a></h3>
                                                    <p class="description">{{object.text|truncatechars:180}}</p>
                                                    <a href="#" class="link"></a>
                                                </div>
                                                <div class="bottom">
                                                    <ul class="meta">
                                                        <li class="meta-date">{{object.created_at|naturaltime}}</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                </div>
                                {%endfor%}

                            </div>
                        </div><!-- Container End -->
                    </div><!-- Inner End -->
                </div><!-- Outer End -->
            </section><!-- Section: Blog End -->

        </div><!-- Site Content End -->
        {% include 'partials/footer.html'%}
        <!-- Site Footer End-->

    </div><!-- Site Wrapper End -->


</body>
{% endblock %}

templates/partials/header.html
{% load static %}
<header class="pr__header pr__dark" data-uk-sticky="top: 100vh; animation: uk-animation-slide-top;">
  <div class="uk-container">
    <div class="inner">
      <div class="logo" style="height: 100px; width: 100px; padding-top: 15px;">
        <a href="/">
          <image src="{%static 'assets/logo.png'%}"></image>
        </a>
      </div>

      <div class="navbar pr-font-second">
        <nav class="menu" data-uk-scrollspy-nav="offset: 0; closest: li; scroll: true">
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'website:about' %}">About</a></li>
            <li><a href="{% url 'website:service' %}">Services</a></li>
            <li><a href="{% url 'website:project' %}">Projects</a></li>
            <li><a href="{% url 'website:blog' %}">Blog</a></li>
            <li><a id="pr__contact" href="#pr__contact__form" data-uk-toggle="">Contact</a></li>
          </ul>
        </nav>

      </div>
      <div class="navbar-tigger" data-uk-toggle="target: #navbar-mobile">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
</header>
<div id="pr__contact__form" class="pr__contact__form pr__dark uk-modal-full" data-uk-modal="">
  <div class="uk-modal-dialog" data-uk-height-viewport="">
    <div class="form-outer">
      <div class="uk-container uk-container-xsmall">
        <div class="form-inner uk-position-relative">
          <button class="uk-modal-close-full" type="button" data-uk-close="ratio: 2;"><span>Close</span></button>
          <h2 class="uk-modal-title uk-h1">Let's Talk?</h2>
          <p>Let’s make something awesome together</p>
          <form class="pr__contact pr__form" action="mailto:info@bakpagelabs.com" method="POST">
            <div class="pr__form__group">
              <label for="name">Your Name <span class="required">*</span></label>
              <input class="pr-input" id="name" name="name" type="text" />
            </div>
            <div class="pr__form__group">
              <label for="email">Your E-Mail <span class="required">*</span></label>
              <input class="pr-input" id="email" name="email" type="text" />
            </div>
            <!-- 
              <div class="pr__form__group">
                <label for="subject">Your Subject <span class="required">*</span></label>
                <input class="pr-input" id="subject" name="subject" type="text" />
              </div>
              <div class="pr__form__group">
                <label for="budget">What's your budget range?</label>
                <select class="uk-select" id="budget" name="budget">
                  <option>&nbsp;</option>
                  <option>Low budget</option>
                  <option>$1,000 — $2,000</option>
                  <option>$2,000 — $5,000</option>
                  <option>$5,000 — $10,000</option>
                  <option>$10,000+</option>
                </select>
              </div> -->
            <div class="pr__form__group">
              <label for="message">Your message <span class="required">*</span></label>
              <textarea class="pr-textarea" id="message" name="message"></textarea>
            </div>
            <p class="pr__form__group uk-margin-large">

            </p><input class="uk-button uk-button-large uk-button-primary" type="submit" name="submit"
              value="Submit"></input>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

templates/partials/loader.html
<div id="loader" class="preloader pr__dark">
  <span class="loading">
    <span class="txt">BakPage Labs</span>
    <span class="progress">
      <span class="bar-loading"></span>
    </span>
  </span>
</div><!-- Preloader End -->

templates/partials/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  {{ message }}
</div>
{% endfor %}

templates/partials/mobile_nav.html
<div class="pr__mobile__nav" id="navbar-mobile" data-uk-offcanvas="overlay: true; flip: true; mode: none">
  <div class="uk-offcanvas-bar">

    <button class="uk-offcanvas-close" type="button" data-uk-close="ratio: 2;"></button>

    <nav class="menu" data-uk-scrollspy-nav="offset: 0; closest: li; scroll: true">
      <ul data-uk-scrollspy="target: > li; cls:uk-animation-slide-right; delay: 100; repeat: true;">
        <li><a href="#pr__hero">Home</a></li>
        <li><a href="#pr__services">Services</a></li>
        <li><a href="#pr__works">Works</a></li>
        <li><a href="#pr__about">About</a></li>
        <li><a href="blog/">Blog</a></li>
        <li><a id="pr__contact" href="##pr__contact__form" data-uk-toggle="">Contact</a></li>
      </ul>
    </nav>

  </div><!-- Off Canvas Bar End -->
</div>